spring:
  datasource:
    #  指定数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接信息
    url: jdbc:mysql://175.178.0.51:3306/guimall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: guimall
    password: MTAMZP3XjcZ5kyCe
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 120000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      keep-alive: true
      keep-alive-between-time-millis: 60000
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  security:
    user:
      name: admin #登录用户名
      password: admin #登录密码
minio:
  endpoint: https://img.zouyua.icu
  accessKey: admin
  secretKey: password
  bucketName: weblog-gq
# 溯源二维码配置
trace:
  # 前端访问地址（需配置内网穿透域名，如 https://your-domain.fy.takin.cc）
  frontend-base-url: http://localhost:5173
alipay:
   # 应用ID
  app-id: 9021000162659364
#  app-id: 9021000162647538
   # 应用私钥（从密钥工具生成）
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCGWerjHZxoBw/cih6SFP6XLPG8C99gCCSpZph4XIsx7H0lcKOKysIZgX3uIuZiT0MbIkojzZGz2/4glNzBLAys+0860a7fCA0PwcAu8YBCu1q9M9wycl9Rc+Ftu9Y2uLoJUcO1dL8lJhGi9/BrJA+WaaDnlrDQ4wFlfBrpa5bFOwWr2/L3fj2SL9tsoz4gBwJV6EOPnDmpzdDjSNKM27Zilz+Vlb1X9enL9HtZqqaQw3CSfE40tFyPfM2ys2PhM8dvSO7pDfN7/mwBABGJbjGaqiR8Gt0VLcD5myRWBBLONFV7MibHtErpgQ7H+Jqng5gr6bKKBPsoqIQEZyfmOIGXAgMBAAECggEAG36jVz9kFtX7JQMPJo4tW/rSrc0wNZL1DcX1RgyKX/kp01Ot5GWCO34Iq4dw5oWaEh9+VL1pKAnJhBly5AWDwpLbsAnhY7teEO9xySmbOgzlkPrgAWLupti0NaTPPfun9uhIyQXPaGbWDSf4h7Sli/6p8zsfjGAolQBE8agW/t26+w3kuJ6UZhjwBqZ7H0mJdDlhBgp7MXrkaUhLlA5BSrBNKgSLLOLbk2UmDnNsq4haRZfCFQeHNEYCyaaaqzutOEJU3BPjvS3eNtjPmo3TG+moP0a7ztIQquU9XFfqm65FmJf9pRnfh+cqEMFRgYII/gb415tTZAjthRSo5l0tgQKBgQDu+rqhlXTHXQmWiSD8u/sd4YFQIkV1XMQpbtnpJe7KgQCwLz8bSqH5rysz7DYvQoBGRUq8t5eXhtuyCGtbX58weSMg9Q9gyr4UpwGaDLoQXJ7ODqneNaz3XtZc0eFDCveAFpP5VA/i+KHRetrDJxDUYT19BO+5nSuY4AJhNomAEQKBgQCP64VXD6tNpzCwPng4RX56mcJk0TatKvItwBUIKgo2wxggzSYNS741KnBhZOAiuvbvF/Byx/sEyhNr1rCzzKnh8B/ne/VqIWDNJS3BtgPOmVf9T02CsvSemfgBSFR1cuav2ci85ERYoxjE+dS7bXIuwZZ4lPXlQB/4sazP8XUPJwKBgQCVc3WtwYLTfsqVOtLHW2PyzukIzTX07Hu8kZdzaAaK29wrUpC7p5PeSv7QrONB8Ou5hnHzzTjfSTYxg3RoI0exj8A5RyhD1ubCkaK9zUG7I8EoiiEPVzABT2zthU/DlqMrlnMZ1MlOn0DLeXI/4zlyKBHFEoY85R6zrzutweaBkQKBgDwMyHEgH5jiBsWy+xR3oqNjHqJUTR0KC0ydlej3KZXZ52pgTt1DWlTypTtuDLtRCZGPiotJ9+nyqxHW3ZnX7pZQS++ZYDftP2e5eJMX8BS3FOijuzKqmrjGg519YYgz7h83nrN6By54tvARUfr2Wqs5qSAc/1CtZemtsO5+0BoHAoGAUHHn+RulvEEabT+E7ThK8g6dw8tXk9yTieILzHzclS7AvYyyM4v8LB3a9YP+GUknr8Q49tTcngSZi8PCCcOzuBjWC+2zVWx/YyfUnHjk2EkYeJMt7Xl1s7h4hz97o2TJ7mAe/eGMCsFEb08yPj/qledgPOw0a9toqlcbhdQMgCM=
#  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEMfpBpj3OwU+M40zYKLIaeeiihQg3C1RMUO8Nw25+Wnax8LOx/Y1hZYjokN3YNZGu2MYE/Gd/PFWHfJ9I2zGUWi5Lu9d8M4Ph9Y6NlIdV9q23FtnRXSkJH87kHb0gRk3IGswpHDKLEweU88aXswOeANsDm2Gcef9+9Oo0wtuHZS3opCIgvxsTK6mOKJFU1U6Gj+qk8N6tadHPHSxEyDPNfmhxir0Zv9FFTzE/VKgzEcARCudVCcb/6DjRiazQqP+GSQtW4e5jqyR0oHhwbwZ3yRuNihPW6I0VKMEsxoAH2nRgQnzNbwtDbKX+iyalXvkPdUSIOARgJwPkckQbLTfxAgMBAAECggEAUiSWocvnjtwy4Ur9jncjcqBd/UVzlhBBQB6WqA2OAor/rSqZIcmF2yR2uOCGcZKkJy+NYOMItiXdrXdI/WkAjhtfzMedxduPuRhlkfOA4kYAn2qK0fSOTMqrhajJ2Wx1/nTxy7iJlN7nyr5yBGun9Qxopk71BF2z0kTaljKLVVkUu/u5wLF614hTThD+CgtUMTYItS9Afv/cMrdyRYOiOVANEWYz6tPJgBM+zsNiXOQka8XnI/lxXEoS1eOClW+ZQ+spc5RNyJrmCpvNm8Nn/mOJFf29y+M3rd96i4xAhxvnLNFW2ImwbNy+LOGsN/D1QCzIPPnD4lUxdULkOrf+3QKBgQDjLiCKCHak/aunnnhf+2XWHvBlrlJWrpzm4BdrcZX1oszGkNo5SnphzH1SGDvnbZbbFq+wm3HOWBjAIL2bMHVxeVNgfD6wg1FJ600mRiS5xGvcCJFYAMfigAmIL9nF7Dxjz+hOfhshQc7E7YKsyrGPZ4TzfRej4GYpUqWnYc3xjwKBgQDdFZZNhJmF1SHcubZxV46EhOXbfr3AbcjGAEIGFJIqMTQYtPx8ABZh3G+yCKbc9qSwYJ34HSo9liLB3U5rkyNS538eo5zk4WFW5dKKNpiY8hCXFXkThW8kqXM5XslnWWxaWxMLXvgGfozhRBZNQu1BMQVeu4ZTKBI/sNrYSgJ+fwKBgQCg+YBpDpIzWuQVA788E8EXNhkVk64YaeYX2lX99iBSS6daVC2tRs7tGZ77Wtynogmw+KRJOfwsQFRZX1m6611sqJGh3qf1HzesbyTdp/pB/6KF6TRD7Vm1bxBSBcYD7t7jwuBTLhw/NogzFjDwCzhB6xJUDiGAJ3N8eGmU70KklQKBgFvA/MsZMBoCFXakwJoTi3tmKHtLA3dcWMoMC1q4qNzH5OYoHu1bn+5nbRfHTXFBD6J/xq/VctVyfORWc5hjzXI3z2Mo5hF7lElbQmDIPdakB8ycRc6bP0BI7yAtPYsd6sEpMSMz+92+IbvP5S2VjB/VN3RUgW/7nm8+d+Tx+k0DAoGBAKyS+Eo5PhiI3CDgxU30zARQkaukHILkD6Ha2/q1qopchJovMDNxELOF2jwrIm1Ly6rLguMOo40Sve2jLvJ+gShVJ/ubv/dsX64wfbOin4X0CFDGxxOm0toGBIOPvJH4mo8RcNPPvCyY0iNd4pI631fcZGzJkq4aku06EqiVVAYZ
  # 支付宝公钥（从开放平台获取）
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwaTqRZN/NrIyLnBH7P8ZoD3NHvkyzvd7QegKRb47jXvjHIhL+LcTlws9z9sPgB6ud5+Yb7YOHFpINpUeeHMxTA0sdYJ1sS5K+1wNzoq+moC7kNWlHxEhaY1v1zFmvbQlp3i+XMNUptaVMK7J0/zqrzccWBOwTs5PPxHZMBcy3eWDuKdf3JxuHq5XlFyepnSSQC3BYAge/BzdIeWa8TTFxIoyHM/hCFdx8ORUCRJHsYHsza35285cRafixIPXf9h0CoKdIx4UA49nPk8Nj7s3S+U/DeAT2eqRPJkeeyG+6e4YTUTK6XyknFwvQPti6kCKcfCiDhn8DVwQmNZWGSTaIQIDAQAB
#  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiEsDK+6PvjcdwmxLBu0F7rlpmZeBeIHASJoCkCX7fO0rV4CE5ykLmA/OhInTgxfhDxXP4NCMzq3d0fKAMoYre4R4Ss/f9vDd5WqIZM+4DN9xTOiDXk/VWBgYWyoLVO6fBqCPN8kozjRE6Yd5Mg9qcGd/HCJngoVPTN6fnhlnuW/Qvj7Z9cwqwIElxOew+NvUJOBWwkhqz4Hnla3lF8cBkshueXPyS8Q8WvmKCPp6IStcohusxyRm7f1qKL0udwmTw6EmOo8mJ6Qd11rBpO0L+IIopDFjI6NBee0z22f4JWzrJUfcHNa+Caaxs1F99emi6k30pxJJ45uFD7Lxr9B8ywIDAQAB
  # 服务器异步通知页面路径（zeronews 内网穿透地址）
  notify-url: "https://uz6ekror18.fy.takin.cc/alipay/notify"
#  notify-url: "https://n13ozanibc.fy.takin.cc/alipay/notify"
   # 页面跳转同步通知页面路径
  return-url: "http://localhost:5173/#/pay/result"
   # 签名方式
  sign-type: "RSA2"
  # 字符编码格式
  charset: "UTF-8"
  # 支付宝网关（沙箱环境）
  gateway-url: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"

rocketmq:
  name-server: 175.178.0.51:9876 # name server 地址
  producer:
    group: guimall_group
    send-message-timeout: 3000 # 消息发送超时时间，默认 3s
    retry-times-when-send-failed: 3 # 同步发送消息失败后，重试的次数
    retry-times-when-send-async-failed: 3 # 异步发送消息失败后，重试的次数
    max-message-size: 4096 # 消息最大大小（单位：字节）
  consumer:
    group: guimall_group
    pull-batch-size: 5 # 每次拉取的最大消息数
